[package]
name = "context-hub-fuse"
version = "0.1.0"
edition = "2021"

[dependencies]
context-hub-core = { path = "../context-hub/context-hub-core" }
fuser = "0.14"
libc = "0.2"
uuid = { version = "1", features = ["v4"] }
