name: Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.10'
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  # Build Docker images in parallel - no dependency on infrastructure
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_tag: worker-task
            context: .
            file: ./Dockerfile.worker
          - image_tag: chainlit-client
            context: .
            file: ./chat_client/Dockerfile
          - image_tag: voice-ws
            context: ./agents/voice-agent/websocket-server
            file: ./agents/voice-agent/websocket-server/Dockerfile
          - image_tag: voice-webapp
            context: ./agents/voice-agent/webapp
            file: ./agents/voice-agent/webapp/Dockerfile
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az acr login --name vextiracrdev
          
      - name: Build and push ${{ matrix.image_tag }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: |
            vextiracrdev.azurecr.io/${{ matrix.image_tag }}:${{ github.sha }}
            vextiracrdev.azurecr.io/${{ matrix.image_tag }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  # Deploy infrastructure - can start immediately, just needs to wait for images at the end
  deploy-infrastructure:
    runs-on: ubuntu-latest
    outputs:
      pulumi-configured: ${{ steps.setup.outputs.configured }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Cache Pulumi dependencies
        uses: actions/cache@v3
        with:
          path: |
            infra/.venv
            azure-function/.python_packages
          key: ${{ runner.os }}-pulumi-${{ hashFiles('infra/requirements.txt', 'azure-function/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pulumi-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt
          
      - name: Install function dependencies
        run: |
          pip install -r azure-function/requirements.txt \
            --target azure-function/.python_packages \
            --platform manylinux2014_x86_64 \
            --implementation cp \
            --python-version ${{ env.PYTHON_VERSION }} \
            --only-binary=:all: \
            --upgrade
            
      - id: setup
        name: Setup Pulumi stack and config
        run: |
          cd infra
          pulumi stack select dev --create --non-interactive
          
          # Set all config at once
          pulumi config set domain "vextir.com"
          pulumi config set aadClientId "$ARM_CLIENT_ID" --secret
          pulumi config set aadClientSecret "$ARM_CLIENT_SECRET" --secret  
          pulumi config set aadTenantId "$ARM_TENANT_ID"
          pulumi config set openaiApiKey "${{ secrets.OPENAI_API_KEY }}" --secret
          pulumi config set twilioAccountSid "${{ secrets.TWILIO_ACCOUNT_SID }}" --secret
          pulumi config set twilioAuthToken "${{ secrets.TWILIO_AUTH_TOKEN }}" --secret
          
          # Use placeholder images initially - will be updated after build
          pulumi config set workerImage "mcr.microsoft.com/azuredocs/aci-helloworld:latest"
          pulumi config set uiImage "mcr.microsoft.com/azuredocs/aci-helloworld:latest"  
          pulumi config set voiceWsImage "mcr.microsoft.com/azuredocs/aci-helloworld:latest"
          
          echo "configured=true" >> $GITHUB_OUTPUT
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          
      - name: Deploy baseline infrastructure
        run: |
          cd infra
          pulumi up --yes --skip-preview
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  # Final deployment with actual images
  deploy-with-images:
    runs-on: ubuntu-latest
    needs: [build-images, deploy-infrastructure]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python  
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Restore cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            infra/.venv
            azure-function/.python_packages
          key: ${{ runner.os }}-pulumi-${{ hashFiles('infra/requirements.txt', 'azure-function/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pulumi-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r infra/requirements.txt
          
      - name: Update images and deploy
        run: |
          cd infra
          pulumi stack select dev --non-interactive
          
          # Update to real images
          pulumi config set workerImage "vextiracrdev.azurecr.io/worker-task:${{ github.sha }}"
          pulumi config set uiImage "vextiracrdev.azurecr.io/chainlit-client:${{ github.sha }}"
          pulumi config set voiceWsImage "vextiracrdev.azurecr.io/voice-ws:${{ github.sha }}"
          
          # Deploy with real images
          pulumi up --yes --skip-preview
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}